### ISSUE TITLE
Error al ingresar a la web

### ISSUE THREAD

**Issue by castromaciel** [Ibrandandev/ProyectoFinal-g2-frontend#12]
## Proceso

1. Ingresar a la url

## Resultado esperado

Se espera que la página web cargue con normalidad

## Resultado actual

Muestra un cartel de error, y un error de cors

## Captura

<img width="1438" alt="image" src="https://github.com/Ibrandandev/ProyectoFinal-g2-frontend/assets/83432755/b9a268bd-90d1-4b02-8003-95b77284a015">

<img width="1438" alt="image" src="https://github.com/Ibrandandev/ProyectoFinal-g2-frontend/assets/83432755/5273f977-95a6-416e-9d0d-763fb2830326">

> Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by Ibrandandev** [comment]
Buenas tardes Maciel, la base de datos estuvo en pausa por el tiempo que pasó. Ya se encuentra activa

**Comment by castromaciel** [comment]
@Ibrandandev Tener en cuenta lo siguiente. 
Cuidado con las actualizaciones de los estados dentro de los `useEffect`.

https://github.com/Ibrandandev/ProyectoFinal-g2-frontend/assets/83432755/8ad8d780-ae4f-49fd-95e0-be837b246735

**Comment by castromaciel** [comment]
Ocurre lo mismo en la pantalla de servicios:

<img width="1434" alt="image" src="https://github.com/Ibrandandev/ProyectoFinal-g2-frontend/assets/83432755/628130d4-e5c5-4062-b60a-2ab0ecca2c78">

**Comment by Ibrandandev** [comment]
Hola Maciel, realicé la modificación de las dependencias en los useEffect. Espero Respuesta, gracias!

**Comment by Ibrandandev** [comment]
Buneas tardes Maciel! Las depencias de los useEffect fueron actualizadas. Saludos!
