### ISSUE TITLE
Color de cabecera "Comentarios"

### ISSUE THREAD

**Issue by castromaciel** [Ibrandandev/ProyectoFinal-g2-frontend#13]
## Proceso

Navegar por el home del sitio web

## Resultado esperado

Asegurar de que la página sea legible, para ello entre los textos, titulos y el color del fondo debe haber suficiente contraste. Si el contraste es bajo, el texto puede resultar difícil de leer.

## Resultado actual

El texto "Comentarios" no es muy legible.

## Captura

<img width="324" alt="Screenshot 2024-01-09 at 10 47 57" src="https://github.com/Ibrandandev/ProyectoFinal-g2-frontend/assets/83432755/0da8aba2-da9d-4473-912f-0544fa42ee3c">

> Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by Ibrandandev** [comment]
Titulo cambiado a color Naranja
