### ISSUE TITLE
Espaciado en el login

### ISSUE THREAD

**Issue by castromaciel** [Ibrandandev/ProyectoFinal-g2-frontend#14]
## Proceso

1. Ingresar desde un dispositivo movil
2. Dirigirse al login

## Resultado esperado

El espaciado entre textos, es importante para mejorar la legibilidad y estética del diseño. Se recomienda proporcionar un espacio visualmente agradable entre el contenido y los bordes del elemento, o entre elementos, evitando que el texto o el contenido se sientan demasiado pegados a los límites del contenedor.

## Resultado actual

En el login, el texto olvidó su contraseña y el botón Iniciar Sesión, no tienen espaciado vertical

## Captura

<img width="296" alt="image" src="https://github.com/Ibrandandev/ProyectoFinal-g2-frontend/assets/83432755/aa46e1f1-de3e-4666-aaf2-d99315504aa1">

> Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by Ibrandandev** [comment]
Corregido!!
